[package]
name = "fem_comp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.32.5"
nalgebra-sparse = {version = "0.9.0", features = ["io"] }
calamine = "0.24.0"
